### ISSUE TITLE
Publish as a .NET Core (2.1) Global Tool

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/t5#3]
[T5.TextTransform.Tool](https://www.nuget.org/packages/T5.TextTransform.Tool/1.1.0) is currently available for .NET Core as `dotnet-tt` using the [CLI tools extensibility model](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility). .NET Core 2.1 introduces [.NET Core Global Tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) but which seems incompatible. Running `dotnet tool install -g T5.TextTransform.Tool` ends up in the following error:

```
error NU1212: Invalid project-package combination for T5.TextTransform.Tool 1.1.0. DotnetToolReference project style can only contain references of the DotnetTool type 
dotnet : The tool package could not be restored.
At line:1 char:1
+ dotnet tool install -g T5.TextTransform.Tool
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The tool package could not be restored.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Tool 't5.texttransform.tool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by th
is name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

Consider making T5.TextTransform.Tool available as a .NET Core Global Tool (so it can be run like `dotnet tt`) without compromising the existing ability to use on .NET Core 2.0, especially as a [per-project tool via `<DotNetCliToolReference>`](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility#consuming-per-project-tools).

**Comment by atifaziz** [comment]
Per NuGet/Home#6630, seems like the language for NU1212 is being clarified:

    The requested package does not have the expected DotnetTool type and can't be used where that type is expected. For example, this package can't be used with "dotnet install tool -g"

**Comment by atifaziz** [comment]
Per dotnet/cli#9464, it appears that the only solution is to publish two separate packages as each package requires a distinct type. For the global tool version, a name other than **T5.TextTransform.Tool** will be needed, and ugly as it seems, I'm currently thinking **T5.TextTransform.DotNetTool**. 🤔 @0xced Do you have another suggestion?

**Comment by 0xced** [comment]
How about `dotnet-tt` for the new global tool package? I saw @nil4 used [dotnet-xdt](https://www.nuget.org/packages/dotnet-xdt) for his Xml Document Transformation global tool.

**Comment by konard** [comment]
[dotnet-t4-project-tool](https://github.com/mono/t4) is just so much better.

**Comment by atifaziz** [comment]
Closing in agreement with @Konard.
