### ISSUE TITLE
Generation error if parameter directive is used

### ISSUE THREAD

**Issue by itn3000** [atifaziz/t5#8]
# Environment

* T5.TextTransform.Tool = 1.1.0

# Steps to reproduce

1. generating new c# console project
2. add `T5.TextTransform.Tool-1.1.0` to PackageReference
3. create tt
4. run `dotnet tt -a Namespace=abc`

the tt file is following.

```
using System;

<#@ import namespace="System" #>
<#@ parameter Type="System.String" name="Namespace"#>
<#
    var ns = Namespace;
#>
namespace <#=ns#>
{
}
```

# Exepcted Result

output following cs file.

```csharp
using System;
namespace abc
{
}
```

# Actual Result

compilation was failed and output following error message.

```
Processing '.\hoge.tt' failed.
(66,34): ERROR The type or namespace name 'Remoting' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
```

[.NET Remoting is not currently supported in .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/libraries), but [t4's implementation seems to use it in processing parameter directive](https://github.com/atifaziz/t5/blob/6f93925ad1ecbd676013e1c3abc3fbfc75f9ba39/src/TextTemplating/Microsoft.VisualStudio.TextTemplating/ParameterDirectiveProcessor.cs#L134).

**Comment by atifaziz** [comment]
Seems to generate this code:

```c#
public partial class GeneratedTextTransformation6838cd33 : global::Microsoft.VisualStudio.TextTemplating.TextTransformation {


        private string _NamespaceField;

        public string Namespace {
            get {
                return this._NamespaceField;
            }
        }


    public override string TransformText() {
        this.GenerationEnvironment = null;

        #line 1 "T:\foo.tt"
        this.Write("using System;\r\n\r\n");

        #line default
        #line hidden

        #line 5 "T:\foo.tt"

    var ns = Namespace;


        #line default
        #line hidden

        #line 8 "T:\foo.tt"
        this.Write("namespace ");

        #line default
        #line hidden

        #line 8 "T:\foo.tt"
        this.Write(global::Microsoft.VisualStudio.TextTemplating.ToStringHelper.ToStringWithCulture(ns));

        #line default
        #line hidden

        #line 8 "T:\foo.tt"
        this.Write("\r\n{\r\n}\r\n");

        #line default
        #line hidden
        return this.GenerationEnvironment.ToString();
    }

    public override void Initialize() {
        base.Initialize();
            if ((this.Errors.HasErrors == false)) {
                bool _NamespaceAcquired = false;
                if (((this.Session != null)
                            && this.Session.ContainsKey("Namespace"))) {
                    object data = this.Session["Namespace"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._NamespaceField = ((string)(data));
                        _NamespaceAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'Namespace\' did not match the type pass" +
                                "ed to the template");
                    }
                }
                if ((_NamespaceAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._NamespaceField = ((string)(data));
                            _NamespaceAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'Namespace\' did not match the type pass" +
                                    "ed to the template");
                        }
                    }
                }
            }

    }
}
```

The problematic line being:

```c#
object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
```

Fix probably belongs in `ParameterDirectiveProcessor.ProcessDirective`:

https://github.com/atifaziz/t5/blob/0de9b9e9a576f93dd17c0d0c33beb7380b2fd972/src/TextTemplating/Microsoft.VisualStudio.TextTemplating/ParameterDirectiveProcessor.cs#L105-L184

A replacement or emulation for `CallContext` for .NET Core could be the quickest solution, and @kzu discusses one in his blog entry titled, “[How to migrate CallContext to .NETStandard and .NETCore](http://www.cazzulino.com/callcontext-netstandard-netcore.html)”.

@mhutch [doesn't seem to have gotten round to addressing it](https://github.com/mono/t4/blob/5fd2a248de760cecc3e04e76a7cb9837bd91a2a5/Mono.TextTemplating/Microsoft.VisualStudio.TextTemplating/ParameterDirectiveProcessor.cs) either in the [`dotnet-texttransform`](https://github.com/mono/t4/tree/dotnet-texttransform) branch of [Mono.TextTemplating](https://github.com/mono/t4).

Thoughts on implementation/workaround & PR welcome. 😄

**Comment by mhutch** [comment]
Coincidentally I fixed it before I saw this 😁

https://github.com/mono/t4/commit/086b6f941cc49c1736333b78cf001b0e748d362b

**Comment by mhutch** [comment]
(btw, have you considered upstreaming your changes?)

**Comment by atifaziz** [comment]
> Coincidentally I fixed it before I saw this 😁
>
> mono/t4@086b6f9

Thanks for the pointer! Unfortunately, that doesn't seem to quite cut it because it completely bypasses the generation of the following code:

```c#
                if ((_NamespaceAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._NamespaceField = ((string)(data));
                            _NamespaceAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'Namespace\' did not match the type pass" +
                                    "ed to the template");
                        }
                    }
                }
```

This means that parameter values can only be set via session, but [session support is disabled](https://github.com/mono/t4/blob/da7f3dc6ced80018b073ff6b79c566a93a87334d/TextTransform/TextTransform.cs#L71
):

https://github.com/atifaziz/t5/blob/0de9b9e9a576f93dd17c0d0c33beb7380b2fd972/src/TextTransform/TextTransform.cs#L71

> (btw, have you considered upstreaming your changes?)

I did a while back! :smile: See my comment on mono/t4#8:

> https://github.com/mono/t4/issues/8#issuecomment-363590843

Are you talking about specific changes? What's your proposal?

**Comment by mhutch** [comment]
> This means that parameter values can only be set via session, but [session support is disabled](https://github.com/mono/t4/blob/da7f3dc6ced80018b073ff6b79c566a93a87334d/TextTransform/TextTransform.cs#L71):

Fixed that one already too: https://github.com/mono/t4/commit/9bb14ca76bc518182445d9b54e0795383beb7a71

In general I feel like the `CallContext` stuff was designed to pass data to templates running in AppDomains and doesn't make much sense without them, as there are other mechanisms.

> I did a while back! 😄 See my comment on [mono/t4#8](https://github.com/mono/t4/issues/8):
> 
> > [mono/t4#8 (comment)](https://github.com/mono/t4/issues/8#issuecomment-363590843)
> 
> Are you talking about specific changes? What's your proposal?

Nothing specific! I just think it would be good tp be collaborating rather than competing, if our goals aren't too different :)

**Comment by atifaziz** [comment]
> Nothing specific! I just think it would be good tp be collaborating rather than competing, if our goals aren't too different :)

I'd rather collaborate than compete any day. You know T4 inside-out so I would lose the race anyhow. :wink: As I said in my [comment](https://github.com/mono/t4/issues/8#issuecomment-363590843), I didn't want to take the burden of maintaining a version that supported .NET/Mono simply because I wouldn't have the time to dedicate the needed cycles. T5 really started because I wasn't too sure when you'd get the time to pick up the project again and I needed something more urgently. Now that T4 seems to be getting back some more love from you, I'd be happy to bury T5 as a stop-gap solution.
